// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQiZVQYZ_glyOOqqbXxk4-iODXpv5LK-g',
    appId: '1:465407421043:android:15d22e4ae3dc6618255806',
    messagingSenderId: '465407421043',
    projectId: 'demoapp-ffc17',
    authDomain: 'demoapp-ffc17.firebaseapp.com',
    storageBucket: 'demoapp-ffc17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQiZVQYZ_glyOOqqbXxk4-iODXpv5LK-g',
    appId: '1:465407421043:android:15d22e4ae3dc6618255806',
    messagingSenderId: '465407421043',
    projectId: 'demoapp-ffc17',
    storageBucket: 'demoapp-ffc17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'INSERT_IOS_API_KEY_HERE',
    appId: 'INSERT_IOS_APP_ID_HERE',
    messagingSenderId: '465407421043',
    projectId: 'demoapp-ffc17',
    storageBucket: 'demoapp-ffc17.appspot.com',
    iosClientId: 'INSERT_IOS_CLIENT_ID_HERE',
    iosBundleId: 'com.example.yourapp',
  );
}